function [ A, TXY ] = solve( W, P, Q )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
Px = P(1, :);
Py = P(2, :);
Qx = Q(1, :);
Qy = Q(2, :);

H_tilda = 2 * [ ...
    sum(W .* Px .^ 2), sum(W .* Px .* Py), sum(W .* Px); ...
    sum(W .* Px .* Py), sum(W .* Py .^ 2), sum(W .* Py); ...
    sum(W .* Px), sum(W .* Py), sum(W)];

H = [ H_tilda, zeros(3); zeros(3), H_tilda ];

f = -2 * [ ...
    sum(W .* Px .* Qx); ...
    sum(W .* Py .* Qx); ...
    sum(W .* Qx); ...
    sum(W .* Px .* Qy); ...
    sum(W .* Py .* Qy); ...
    sum(W .* Qy)];

%options = optimset('Algorithm', 'interior-point');
options = optimset('LargeScale', 'off', 'Display', 'off');
abcdef = quadprog(H, f, [], [], [], [], [], [], [], options); %H is matrix, f is vector, 1/2 x'Hx + F'x = sum...
%abcdef = quadprog(H, f); %H is matrix, f is vector, 1/2 x'Hx + F'x = sum...
A = [abcdef(1:3)'; abcdef(4:6)'; 0 0 1];

TXY = A * [Px; Py; ones(1,size(P, 2))];

end